---
- name: Become section
  block:


    - name: Add GitLab Runner GPG key
      apt_key:
        url: '{{ gitlab_runner_gpg }}'
      register: apt_key_result
      until: apt_key_result is succeeded

    - name: Add GitLab Runner repository
      apt_repository:
        repo: '{{ gitlab_runner_repo }}'
        validate_certs: true
  become: true
  tags:
    - always
