---
- name: Become section
  block:
    - name: Add GitLab Runner repository
      apt_repository:
        repo: '{{ gitlab_runner_repo }}'
        validate_certs: true
  become: true
  tags:
    - always
